### ISSUE TITLE
Indentation fails to decrement one level after the full stop

### ISSUE THREAD

**Issue by arranger1044** [textmate/prolog.tmbundle#2]
I've added a scope selector (source.prolog) to the Miscellaneous module of the bundle in order to activate automatic indentation. Whereas increasing the indentation after a neck symbol ':-' followed by a newline works fine, decrementing it after a full stop followed by a newline does not.
Even trying to change the property 'unIndentedLinePattern' to 'decreaseIndentPattern' does not seem to make a difference.

**Comment by infininight** [comment]
Thanks for the note on the missing scope, corrected that.

Looking at prolog syntax futher, properly matching the indentation is not really possible. I've made further improvements to the indentation and disabled indentation correction to help improve usability. Reply back if you have any other issues.

**Comment by arranger1044** [comment]
Thanks for your corrections and annotations. Nevertheless I do not properly understand why properly matching the indentation is not possible (in this case de-indentation). Could you elaborate the reason a little more?

**Comment by infininight** [comment]
The issue is that the indention system in TextMate was designed to handle items that decrease the indent and are themselves unindented. We don't currently have a system to say that that a line decreases the indent starting on the following line.

**Comment by arranger1044** [comment]
Gotcha, thanks for replying and explaining
Il giorno 13/dic/2012, alle ore 08:25, Michael Sheets ha scritto:
